CREATE DATABASE MY_WORK_DB

SELECT * FROM [dbo].[STUDENT EDITED TABLE]

---ANSWERING QUESTIONS---
--1 TOP 5 BEST SUDENTS BASED ON AVERAGE SCORE
SELECT TOP 5 STUDENT_NAME, AVERAGE_SCORE
FROM [dbo].[STUDENT EDITED TABLE]
GROUP BY STUDENT_NAME, AVERAGE_SCORE
ORDER BY AVERAGE_SCORE DESC

--2 PERFORMANCE DISTRIBUTION
SELECT
AVG(MATHS_GRADE) AS AVERAGE_MATHS,
AVG(ENGLISH_GRADE) AS AVERAGE_ENGLISH,
AVG(BIOLOGY_GRADE) AS AVERAGE_BIOLOGY,
AVG(PHYSICS_GRADE) AS AVERAGE_PHYSICS,
AVG(CHEMISTRY_GRADE) AS AVERAGE_CHEMISTRY
FROM [dbo].[STUDENT EDITED TABLE]

--3 COUNT OF STUDENT BY STATUS
SELECT [STATUS], COUNT(STUDENT_NAME) AS NUMBER_OF_STUDENT
FROM[dbo].[STUDENT EDITED TABLE]
GROUP BY [STATUS]
ORDER BY NUMBER_OF_STUDENT DESC

--4 STATUS BY GROUP
SELECT [GROUP], [STATUS], COUNT([STATUS]) AS NUMBER_OF_STUDENT
FROM[dbo].[STUDENT EDITED TABLE]
GROUP BY [GROUP], [STATUS]
ORDER BY NUMBER_OF_STUDENT 

--5 NEW VS OLD STUDENT PERFORMANCE
SELECT NEW_OLD_STUDENT,
AVG(MATHS_GRADE) AS AVERAGE_MATHS,
AVG(ENGLISH_GRADE) AS AVERAGE_ENGLISH,
AVG(BIOLOGY_GRADE) AS AVERAGE_BIOLOGY,
AVG(PHYSICS_GRADE) AS AVERAGE_PHYSICS,
AVG(CHEMISTRY_GRADE) AS AVERAGE_CHEMISTRY
FROM [dbo].[STUDENT EDITED TABLE]
GROUP BY NEW_OLD_STUDENT

--6 CONSIDERATION STATUS
SELECT [CONSIDERATION], COUNT(STUDENT_NAME) AS NUMBER_OF_STUDENT
FROM[dbo].[STUDENT EDITED TABLE]
GROUP BY [CONSIDERATION]
ORDER BY NUMBER_OF_STUDENT DESC
